import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * @typedef {Object} Metadata
 * @property {Object} title - Objeto que contém informações sobre o título da página.
 * @property {string} title.absolute - Título absoluto da página (atualmente vazio).
 * @property {string} title.default - Título padrão da página.
 * @property {string} title.template - Template para o título da página, onde %s será substituído pelo título específico.
 * @property {string} description - Descrição da página.
 */
export const metadata: Metadata = {
  title: {
    absolute: "", // se tiver preenchida, ignorará o default e o template
    default: "Next Tutorial | Kewa Code",
    template: "%s | Kewa",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header style={{ backgroundColor: "green" }}>
            <h1>Header</h1>
          </header>
        {children}
        <footer style={{ backgroundColor: "green" }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
